Name: Push Lists to Cloudflare

on:
  schedule:
    # Chạy vào 00:00 UTC mỗi ngày
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run Sync Script
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # Thêm các biến này để script nhận diện được cấu hình từ GitHub Variables
          USER_DEFINED_ALLOWLIST_URLS: ${{ vars.USER_DEFINED_ALLOWLIST_URLS }}
          USER_DEFINED_BLOCKLIST_URLS: ${{ vars.USER_DEFINED_BLOCKLIST_URLS }}
        run: npm start
        
